### ISSUE TITLE
Need more information on configuration of Clara Train SDK

### ISSUE THREAD

**Issue by SomasekharDS** [aws-quickstart/quickstart-nvidia-imaging-clara-train#9]
Hi Team,

Thanks for the Awesome AWS quick starter guide for Clara Train SDK.

I am trying to configure the Clara Train SDK in my personal aws account before proceeding to configure in my organization account. I have gone through the below Clara AWS deployment document. 

https://s3.amazonaws.com/aws-quickstart/quickstart-nvidia-imaging-clara-train/doc/nvidia-clara-train-on-the-aws-cloud.pdf

I have few questions on the deployment process. 

1.  Is there a way i can schedule/customize  start and end time of  p3.2xlarge instances(for cost saving). 
2.  How to remove/cleanup entire infrastructure created by Clara Cloud formation template. If i click **delete button** on the cloud formation stack, it will clean up entire in infrastructure created by Clara Cloud formation template. Please refer the below screenshot.

![image](https://user-images.githubusercontent.com/24861755/88758280-a7497780-d19a-11ea-8fec-e2456ec5ade5.png)

Appreciate your help..

Thank you..

**Comment by AndySchuetz** [comment]
To your first question, you can use AWS EventBridge and a Lambda function to schedule setup and tear down of the deployment.  See this [tutorial](https://docs.aws.amazon.com/eventbridge/latest/userguide/run-lambda-schedule.html) and [blog post](https://aws.amazon.com/blogs/infrastructure-and-automation/scheduling-automatic-deletion-of-aws-cloudformation-stacks/) for more details.

To your second question, all resources will be deleted if you delete the root stack (or top level) of the CloudFormation stack that is deployed by the quick start.

**Comment by SomasekharDS** [comment]
Many Thanks to your response..
